### ISSUE TITLE
Nav Bar not showing on Mobile devices

### ISSUE THREAD

**Issue by mrnoisytiger** [Zazama/TrueStyle#2]
The navigation bar does not show on any devices that have a small viewport such as the iPhone. Is there any way to fix this?

**Comment by Zazama** [comment]
I'll upload an update tomorrow. Sorry for the trouble.

**Comment by mrnoisytiger** [comment]
Thank you! Keep up the amazing work!

**Comment by mrnoisytiger** [comment]
I think I managed to figure out the problem myself. The bootstrap CSS file has the "collapse" class set at "display: none; visibility: hidden." 

I just put another media query at screens with max-width of 480px, overriding these two things. 

Any idea why the Bootstrap CSS has those attributes set?

**Comment by Zazama** [comment]
I think this was a mistake on my side. The collapse class is used together with Bootstrap Javascript which is not included. This was my first bootstrap theme, I think it was just a "beginner" mistake. My idea behind this was, to hide the Navbar if the screen is too small to show everything in one row. I'll upload the fix soon.
